### ISSUE TITLE
Main page HTML 작성

### ISSUE THREAD

**Issue by lhs8701** [lhs8701/Haedarakbang#2]
## Description
Main page의 HTML 코드 작성 및 캘린더 항목 연동

## Todo
- [ ] 캘린더 django 연동
- [ ] 캘린더 항목에서 'Reservation' 생성 페이지로 전환 가능한지 확인
- [ ] 페이지 구성 : 헤더 [작성 - 'templates/header.html']
- 서비스명
- 로그인 배너
- [ ] 페이지 구성 : 본문 [작성 - 'templates/hdrb/main.html']
- 캘린더

## Referance
참고자료

## ETC
기타사항
