### ISSUE TITLE
기본 환경 설정

### ISSUE THREAD

**Issue by lhs8701** [lhs8701/Haedarakbang#3]
## Description
개발에 앞서, 필요한 기본 환경을 설정함

## Todo
- [ ] 템플릿 디렉토리 생성 및 settings.py에 템플릿 디렉토리 등록 [명명 - 'templates']
- [ ] 스태틱 디렉토리 생성 및 settings.py에 스태틱 디렉토리 등록 [명명 - 'static'] 
- [ ] hdrb 앱 생성 [명명 - 'hdrb']
- [ ] url 분리 : hdrb 앱 아래에 urls 파일 생성 [명명 - 'hdrb/urls.py']
- [ ] views 디렉토리 생성 [명명 - 'hdrb/views']
- [ ] base_views 파일 작성 [명명 - 'hdrb/views/base_views.py']
- [ ] test 목적으로 base_views 파일 내 index()함수 구현 (향후 삭제)
- [ ] 템플릿 상속을 위한 기본 HTML파일 작성 [명명 - 'templates/base.html']
- [ ] 보안 및 가상환경 유지 목적으로 .gitignore 파일 작성

## Referance
참고자료

## ETC
기타사항
