### ISSUE TITLE
Reservation model 및 form 작성

### ISSUE THREAD

**Issue by lhs8701** [lhs8701/Haedarakbang#4]
## Description
예약 정보를 담고 있는 Reservation 모델을 작성하고, 생성 기능을 구현한다.

## Todo
- [x] Reservation 모델 작성 [Reservation]
- 필드
  - 날짜 [date]
  - 예약 시작 시간 [start_time]
  - 예약 종료 시간 [end_time]
  - 인원수 [num_of_people]
  - 합석 여부 [allow_join]
  - 메모 [memo]
  - 작성자 [registrant] (로그인, 로그아웃 구현 후 추가)
- [x] admin 계정 생성 후, Reservation 모델 추가
- [x] forms.py 생성 후, Reservation form 작성 [hdrb/forms.py] [ReservationForm]
- 합석 여부 기본값 True로 설정
- 메모 필드는 null=True, blank=True로 설정

## Referance
참고자료

## ETC
기타사항
